runtime: python3.9

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  YOUR_ENV_VARIABLE_NAME: 'your_value'

instance_class: F2 

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
